services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://user:password@host:port/dbname
      - key: BOT_TOKEN
        value: your_bot_token
      - key: BOT_ADMIN_ID
        value: your_admin_id
      - key: WEBHOOK_URL
        value: https://ksgroupbot.onrender.com